name: create-diagram
description: "Create system architecture diagrams, ERDs, UML diagrams, or general technical diagrams in Excalidraw format"
author: "BMad"

installed_path: "{project-root}/.bmad/bmm/workflows/frame-expert/create-diagram"
shared_path: "{project-root}/.bmad/bmm/workflows/frame-expert/_shared"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

helpers: "{shared_path}/excalidraw-helpers.md"
templates: "{shared_path}/excalidraw-templates.yaml"
library: "{shared_path}/excalidraw-library.json"

variables:
  diagram_type: ""
  component_count: ""
  relationship_type: ""
  notation_standard: ""
  save_location: ""
  theme_choice: ""

default_output_file: "{project-root}/docs/diagrams/diagram-{timestamp}.excalidraw"

standalone: true