name: create-dataflow
description: "Create data flow diagrams (DFD) in Excalidraw format"
author: "BMad"

installed_path: "{project-root}/.bmad/bmm/workflows/frame-expert/create-dataflow"
shared_path: "{project-root}/.bmad/bmm/workflows/frame-expert/_shared"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

helpers: "{shared_path}/excalidraw-helpers.md"
templates: "{shared_path}/excalidraw-templates.yaml"
library: "{shared_path}/excalidraw-library.json"

variables:
  dfd_level: ""
  process_count: ""
  datastore_count: ""
  external_entities: ""
  save_location: ""

default_output_file: "{project-root}/docs/dataflow/dfd-{timestamp}.excalidraw"

standalone: true