name: create-flowchart
description: "Create a flowchart visualization in Excalidraw format for processes, pipelines, or logic flows"
author: "BMad"

# Workflow components
installed_path: "{project-root}/.bmad/bmm/workflows/frame-expert/create-flowchart"
shared_path: "{project-root}/.bmad/bmm/workflows/frame-expert/_shared"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Shared resources
helpers: "{shared_path}/excalidraw-helpers.md"
templates: "{shared_path}/excalidraw-templates.yaml"
library: "{shared_path}/excalidraw-library.json"

# Variables
variables:
  flowchart_type: "" # Will be elicited
  complexity: "" # Will be elicited
  decision_points: "" # Will be elicited
  save_location: "" # Will be elicited
  theme_choice: "" # Will be elicited
  custom_colors: {} # For custom theme

default_output_file: "{project-root}/docs/flowcharts/flowchart-{timestamp}.excalidraw"

standalone: true