name: create-wireframe
description: "Create website or app wireframes in Excalidraw format"
author: "BMad"

installed_path: "{project-root}/.bmad/bmm/workflows/frame-expert/create-wireframe"
shared_path: "{project-root}/.bmad/bmm/workflows/frame-expert/_shared"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

helpers: "{shared_path}/excalidraw-helpers.md"
templates: "{shared_path}/excalidraw-templates.yaml"
library: "{shared_path}/excalidraw-library.json"

variables:
  wireframe_type: ""
  fidelity_level: ""
  screen_count: ""
  device_type: ""
  save_location: ""

default_output_file: "{project-root}/docs/wireframes/wireframe-{timestamp}.excalidraw"

standalone: true